# Generated by Django 3.0.6 on 2020-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecurrenceDemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingtime',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='meetingtime',
            old_name='start',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='meetingtime',
            name='type',
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
